- name: mysql
  hosts: mysql
  become: yes 
  tasks:
    - name: disable module mysql
      ansible.builtin.shell: dnf module disable mysql -y
    - name: Copy mysql repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    - name: install mysql
      ansible.builtin.shell: dnf install mysql-community-server -y
    - name: start and enable mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: change the root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1